export const UPDATE_INPUT = "UPDATE_INPUT";
export type UPDATE_INPUT = typeof UPDATE_INPUT;

export const SET_ENTITIES = "SET_ENTITIES";
export type SET_ENTITIES = typeof SET_ENTITIES;

export const SET_PARSER_MESSAGE = "SET_PARSER_MESSAGE";
export type SET_PARSER_MESSAGE = typeof SET_PARSER_MESSAGE;

export const UPDATE_QUERIES = "UPDATE_QUERIES";
export type UPDATE_QUERIES = typeof UPDATE_QUERIES;

export const UPDATE_STOCK_PRICES = "UPDATE_STOCK_PRICES";
export type UPDATE_STOCK_PRICES = typeof UPDATE_STOCK_PRICES;

export const FETCH_STOCK_PRICE = "FETCH_STOCK_PRICE";
export type FETCH_STOCK_PRICE = typeof FETCH_STOCK_PRICE;

export const SET_STOCK_PRICE = "SET_STOCK_PRICE";
export type SET_STOCK_PRICE = typeof SET_STOCK_PRICE;

export const EXECUTE_QUERY = "EXECUTE_QUERY";
export type EXECUTE_QUERY = typeof EXECUTE_QUERY;

export const ADD_EXECUTION = "ADD_EXECUTION";
export type ADD_EXECUTION = typeof ADD_EXECUTION;

export const REMOVE_EXECUTION = "REMOVE_EXECUTION";
export type REMOVE_EXECUTION = typeof REMOVE_EXECUTION;

export const UPDATE_EXECUTION = "UPDATE_EXECUTION";
export type UPDATE_EXECUTION = typeof UPDATE_EXECUTION;